import Image from "next/image"
import { Inter } from "next/font/google"
import Head from "next/head"
import Navbar from "../components/Navbar"
import Banner from "@/components/Banner"

const inter = Inter({ subsets: ["latin"], variable: "--inter-sans" })

export default function Home() {
  return (
    <>
      <Head>
        <title>Shopit!</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='favicon.png'
          // <a target="_blank" href="https://icons8.com/icon/44049/shop">Shop</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        />
      </Head>
      <main className={`bg-amber-200 ${inter.variable} font-sans`}>
        <Navbar />
        <div className='max-w-contentContainer mx-auto'>
          <Banner />
        </div>
      </main>
    </>
  )
}
