import { Inter } from "next/font/google"
import Head from "next/head"
import Banner from "@/components/Banner"
import { Product } from "../type"
import Products from "@/components/Products"

interface Props {
  productData: Product
}

const inter = Inter({ subsets: ["latin"], variable: "--inter-sans" })

export default function Home({ productData }: Props) {
  return (
    <>
      <Head>
        <title>Shopit!</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='../public/favicon.png'
        />
      </Head>
      <main className={`${inter.variable} font-sans`}>
        <div className='mx-auto max-w-contentContainer'>
          <Banner />
          <Products productData={productData} />
        </div>
      </main>
    </>
  )
}

const API = process.env.NODE_ENV === "production" ? "https://shopit-phi.vercel.app/" : "http://localhost:3000/"

export const getServerSideProps = async () => {
  const productData = await (await fetch(`${API}api/productdata`)).json()

  return {
    props: { productData },
  }
}
